export const types = {
    ADD_TO_SPAM:'ADD_TO_SPAM',
    ADD_TO_TRASH:'ADD_TO_TRASH',
    ADD_TO_CHECKED:'ADD_TO_CHECKED',
    REMOVE_FROM_CHECKED:'REMOVE_FROM_CHECKED',
    STAR_MAIL:'STAR_MAIL',
    MARK_AS_READ:'MARK_AS_READ',
    REMOVE_FROM_SPAM:'REMOVE_FROM_SPAM',
    REMOVE_FROM_TRASH:'REMOVE_FROM_TRASH',
    DELETE_PERMANENTLY:'DELETE_PERMANENTLY',
}