export const types = {
    ADD_TO_SPAM:'ADD_TO_SPAM',
    ADD_TO_TRASH:'ADD_TO_TRASH',
    SHOW_UNREAD_MAILS:'TOGGLE_UNREAD_MAILS',
    SHOW_STARRED_MAILS:'TOGGLE_STARRED_MAILS',
    ADD_TO_CHECKED:'ADD_TO_CHECKED',
    REMOVE_FROM_CHECKED:'REMOVE_FROM_CHECKED',
    STAR_MAIL:'STAR_MAIL'
}